version: '3.1'
services:
    nginx:
        container_name: nginx
        image: nginx:stable
        restart: always
        ports:
            - 80:80
            - 9072:9072
            - 9073:9073
            - 9074:9074
            - 9080:9080
            - 8001:8001
        volumes:
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /Users/kevin/www:/var/www/html
    php:
        container_name: php
        build: build/php/8.0
        volumes:
            - D:/www:/var/www/html
            - ./addon/supervisord.d/:/etc/supervisor/conf.d/
            - ./addon/php/swoole.ini:/usr/local/etc/php/conf.d/swoole.ini
            - ./addon/php/php_80.ini:/usr/local/etc/php/php.ini
#            - ./addon/bash/run.sh:/opt/run.sh
        command: /opt/run.sh
        links:
            - redis
            - mysql
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - D:/data/redis/data:/data
        command:
            redis-server
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_USER: 'sa'
            MYSQL_PASS: '1q2w3e4r'
            MYSQL_ROOT_PASSWORD: "1q2w3e4r"
        volumes:
            - D:/data/mysql:/var/lib/mysql
            - ./addon/mysql/my.cnf:/etc/my.cnf
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - mysql
        environment:
#            MYSQL_USER: "root"
#            MYSQL_PASSWORD: "1q2w3e4r"
            MYSQL_ROOT_PASSWORD: "1q2w3e4r"
            PMA_HOST: mysql
            PMA_USER: "root"
            PMA_PASSWORD: "1q2w3e4r"
        volumes:
            - ./addon/phpmyadmin/config.inc.php:/var/www/html/config.inc.php
    nacos:
        image: nacos/nacos-server:latest
        container_name: nacos
        restart: always
        depends_on:
            - mysql
        environment:
            PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
            SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
            MODE: standalone
            MYSQL_SERVICE_HOST: mysql5.7
            MYSQL_SERVICE_DB_NAME: nacos
            MYSQL_SERVICE_PORT: 3306
            MYSQL_SERVICE_USER: root
            MYSQL_SERVICE_PASSWORD: root
            NACOS_APPLICATION_PORT: 9999
            JVM_XMS: 512m
            JVM_MMS: 320m
        volumes:
            - D:/data/nacos/standalone-logs/:/home/nacos/logs
            - D:/data/nacos/plugins/:/home/nacos/plugins
            - D:/data/nacos/conf/application.properties:/home/nacos/conf/application.properties
        ports:
            - "9999:9999"

    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq
        volumes:
            - D:/data/rabbitmq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_VHOST=my_vhost
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1q2w3e4r

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1q2w3e4r
            ME_CONFIG_MONGODB_URL: mongodb://root:1q2w3e4r@mongo:27017/